all: functions_demo measurings

functions_demo: functions_demo.o graphdb.o
	gcc functions_demo.o graphdb.o -o functions_demo.exe

measurings: measurings.o graphdb.o
	gcc measurings.o graphdb.o -o measurings.exe

functions_demo.obj: functions_demo.c
	gcc -c functions_demo.c

measurings.o: measurings.c
	gcc -c measurings.c

graphdb.o: graphdb.c
	gcc -c graphdb.c

clean:
	del -rf *.o \
	del functions_demo.exe \
	del measurings.exe
